# Generated by Django 3.1.5 on 2021-01-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('data_pub', models.DateTimeField(verbose_name='data da publicacao')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
