# Generated by Django 3.1.5 on 2021-01-26 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20210125_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='reservado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
