# Generated by Django 3.1.5 on 2021-01-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210125_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='reservado_por',
            field=models.IntegerField(null=True),
        ),
    ]
