# Generated by Django 3.1.5 on 2021-01-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210127_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='data_reserva',
            field=models.DateField(),
        ),
    ]
